2023-07-27 01:25:48.938 UTC [2208358] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-27 01:25:48.939 UTC [2208358] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-27 01:25:48.945 UTC [2208358] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-27 01:25:48.954 UTC [2208361] LOG:  database system was shut down at 2023-07-27 01:25:48 UTC
2023-07-27 01:25:48.961 UTC [2208358] LOG:  database system is ready to accept connections
2023-07-27 01:25:49.188 UTC [2208383] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-27 01:25:49.188 UTC [2208383] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-27 01:25:49.188 UTC [2208383] STATEMENT:  SELECT testComplexNumbers();
2023-07-27 01:25:49.242 UTC [2208359] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:25:49.276 UTC [2208359] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.006 s, total=0.035 s; sync files=7, longest=0.004 s, average=0.001 s; distance=4190 kB, estimate=4190 kB
2023-07-27 01:25:49.416 UTC [2208410] ERROR:  not a Python mapping
2023-07-27 01:25:49.416 UTC [2208410] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-27 01:25:49.416 UTC [2208410] STATEMENT:  SELECT test1bad();
2023-07-27 01:25:49.423 UTC [2208410] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-27 01:25:49.423 UTC [2208410] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-27 01:25:49.423 UTC [2208410] STATEMENT:  SELECT test2dom('bar');
